yarnPath: .yarn/releases/yarn-4.0.1.cjs
nodeLinker: pnp
enableGlobalCache: true

packageExtensions:
  "drizzle-kit@*":
    dependencies:
      "drizzle-orm": "*"
  "@drizzle-team/studio@*":
    dependencies:
      "drizzle-orm": "*"
